# Generated by Django 4.1.2 on 2022-12-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[('Sotib olingan', 'Sotib olingan'), ('Sotib olinmagan', 'Sotib olinmagan')]),
        ),
    ]
