# Generated by Django 4.1.2 on 2022-12-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Sotib olingan', 'Sotib olingan'), ('Sotib olinmagan', 'Sotib olinmagan')], max_length=255),
        ),
    ]
